Repository space-metaverse/account-frontend, pull requests merged in 2022-11, with the labels that each got.

#3 Sidenav V 1.0
  layouts/index.ts
  layouts/sidenav/index.tsx
  layouts/sidenav/styles.ts
  pages/_app.tsx
Labels: enhancement

#4 feat(app): profile
  .eslintrc.json
  api/auth.ts
  components/Auth.tsx
  helpers/validate.ts
  layouts/index.ts
  layouts/profile.tsx
  layouts/sidenav/index.tsx
  layouts/sidenav/styles.ts
  layouts/sidenav/types.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/profile/information.tsx
  tsconfig.json
  types/index.ts
Labels: enhancement

#5 feat(topnav): responsive
  layouts/topnav/index.tsx
  layouts/topnav/styles.ts
  next.config.mjs
  pages/_app.tsx
Labels: enhancement

#6 refactor(routes): add disabled routes
  layouts/sidenav/index.tsx
  layouts/sidenav/styles.ts
  layouts/sidenav/types.ts
  layouts/topnav/index.tsx
  layouts/topnav/styles.ts
Labels: bug, enhancement

#7 security settings page
  layouts/sidenav/index.tsx
  pages/profile/security.tsx
Labels: enhancement

#8 feat(information): add responsive
  layouts/profile.tsx
  layouts/sidenav/index.tsx
  layouts/sidenav/styles.ts
  layouts/sidenav/types.ts
  package-lock.json
  pages/_app.tsx
  pages/profile/information.tsx
Labels: enhancement

#11 feat(topnav): add logout
  layouts/topnav/index.tsx
  layouts/topnav/styles.ts
  package-lock.json
  package.json
Labels: enhancement

#12 refactor(profile): add more fields
  api/account.ts
  pages/profile/information.tsx
Labels: enhancement

#13 feat(wallet): connect with wallets
  data/wallets.ts
  helpers/truncate.ts
  layouts/sidenav/index.tsx
  layouts/topnav/index.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/wallet/connect.tsx
  pages/wallet/index.tsx
  public/icons/icon-binance.svg
  public/icons/icon-coinbase.svg
  public/icons/icon-metamask.svg
  public/icons/icon-my-ether-wallet.svg
  public/icons/icon-trust-wallet.svg
  public/icons/icon-wallet-connect.svg
  tsconfig.json
Labels: enhancement

#14 orders list
  .eslintrc.json
  layouts/sidenav/index.tsx
  pages/orders/list.tsx
Labels: enhancement

#15 Profile information sms form
  layouts/profile/styles.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/profile/information.tsx
  pages/profile/security.tsx
  redux/slices/account.tsx
Labels: enhancement

#18 fix(document): translate to en-US
  pages/_document.tsx
Labels: bug

#16 feat(space-ui): apply sidenav and topnav
  api/account.ts
  layouts/profile/index.tsx
  layouts/sidenav/index.tsx
  layouts/sidenav/styles.ts
  layouts/sidenav/types.ts
  layouts/topnav.tsx
  layouts/topnav/index.tsx
  layouts/topnav/styles.ts
  package-lock.json
  package.json
  pages/profile/information.tsx
Labels: enhancement

#20 fix(orders): add column name and remove popup of actions
  package-lock.json
  package.json
  pages/orders/list.tsx
Labels: enhancement

#21 fix(auth): wait for loading of verify token
  api/account.ts
  components/Auth.tsx
Labels: bug

#22 feat(orders): list orders
  api/account.ts
  package-lock.json
  package.json
  pages/orders/list.tsx
  pages/orders/list/[id].tsx
  pages/orders/list/index.tsx
Labels: enhancement
